### ISSUE TITLE
Monorepo with yarn workspaces.

### ISSUE THREAD

**Issue by b2rsp** [FinnWoelm/next-on-netlify#11]
Hey and thanks very much for this project!!

I have a project structure that follows something like this
- WebApp1
- WebApp2
- Components
- Library

And i am using the yarn workspaces to make possible using the components in the webapp1, but when i tried to deploy on netlify is says that its requires aws lamba package. 

I have tried to put the `nohoist` option in webapp1 to prevent the child project packages going to the root and tried locally running the netlify but when i deploy its still failling.

Any idea what can be the issue?
My best regards,
Vitor

**Comment by FinnWoelm** [comment]
Hey @b2rsp,

Happy you like `next-on-netlify` :slightly_smiling_face: 

It sounds like the Netlify Function is not bundling `next-aws-lambda`, which `next-on-netlify` depends on. There's probably a simple way to fix that, but the fix will depend on what directory you are deploying from (webapp1? root?), where your package.json file lies, etc...

Do you by any chance happen to have a repo for me to look at?

**Comment by b2rsp** [comment]
Hey thanks very much for you reply.

I will try to mimic the repo in a public so I can share it.

I will come back at you when I have it.

**Comment by FinnWoelm** [comment]
That sounds great! Doesn't need to be fancy; even something basic will be helpful for me to understand what's happening :)

**Comment by FinnWoelm** [comment]
Hey @b2rsp,

I wanted to check in on this!

How are things going? Is this issue still relevant? Were you able to resolve it? Did you get a chance to put together a basic repo?

Look forward to hearing from you!

**Comment by FinnWoelm** [comment]
Hi @b2rsp,

I'm closing this for now since it's been a bit over two weeks :slightly_smiling_face: 

I hope you figured out a solution to the issue! If you did, it would be great to hear from you (and perhaps share a few insights for others who face the same issue in the future). If you are still facing the issue, feel free to reopen this at any time!
