### ISSUE TITLE
Can't resolve 'pnpapi'

### ISSUE THREAD

**Issue by ericchernuka** [FinnWoelm/next-on-netlify#12]
I just started using this project but ran into a show stopper when running my build.

```
12:45:11 PM: > next build
12:45:12 PM: Warning: No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
12:45:12 PM: Creating an optimized production build...
12:45:55 PM: Failed to compile.
12:45:55 PM: 
12:45:55 PM: ./node_modules/next/dist/lib/resolve-request.js
12:45:55 PM: Module not found: Can't resolve 'pnpapi' in '/opt/build/repo/node_modules/next/dist/lib'
12:45:55 PM: > Build error occurred
12:45:55 PM: Error: > Build failed because of webpack errors
12:45:55 PM:     at build (/opt/build/repo/node_modules/next/dist/build/index.js:13:917)
12:45:55 PM:     at process._tickCallback (internal/process/next_tick.js:68:7)
12:45:55 PM: npm
12:45:55 PM:  ERR! code ELIFECYCLE
12:45:55 PM: npm
12:45:55 PM:  ERR! errno
12:45:55 PM:  1
12:45:55 PM: npm
12:45:55 PM: ERR! sm-lunar-lander@1.0.0 build: `next build`
12:45:55 PM: npm ERR! Exit status 1
12:45:55 PM: npm ERR!
12:45:55 PM: npm ERR!
12:45:55 PM:  Failed at the sm-lunar-lander@1.0.0 build script.
12:45:55 PM: npm
12:45:55 PM:  ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:45:55 PM: npm
12:45:55 PM:  ERR! A complete log of this run can be found in:
12:45:55 PM: npm ERR!
12:45:55 PM:      /opt/buildhome/.npm/_logs/2020-06-01T18_45_55_956Z-debug.log
```
I can't seem to get around this, but I'm also at a loss trying to figure out what the issue really is.

I'm running Next 9.4.4 and Node 12/13

**Comment by FinnWoelm** [comment]
Hi @ericchernuka,

That looks like the error happens during `next build` which is before `next-on-netlify` even starts.

I found a `pnpapi`-related issue here: https://github.com/vercel/next.js/issues/9232
Perhaps that helps.

Otherwise, I'm happy to take a look at your code, if you have a repo to share!


Cheers,
Finn

**Comment by ericchernuka** [comment]
Sorry. This was premature.

**Comment by FinnWoelm** [comment]
No worries! Glad you figured it out :grin: 

Please let me know if you run into any `next-on-netlify` issues down the road. And let me know if you build something awesome — I would love to feature some real-life projects in the README.

By the way, I'm releasing a big update to `next-on-netlify` soon, probably tomorrow. The update will add support for `getStaticProps` and `getServerSideProps`. Not sure if you use those, but if you do, I'm happy to drop a message in this thread once v2.0.0 is out :slightly_smiling_face: 


Happy building!

**Comment by ericchernuka** [comment]
Good to know since I'm about to implement `getServerSideProps` probably tomorrow.

**Comment by FinnWoelm** [comment]
`next-on-netlify` v2 is finally out :tada: :tada: You can see the [full list of changes in the changelog](https://github.com/FinnWoelm/next-on-netlify/blob/master/CHANGELOG.md#200-2020-06-02). 

You'll need to make some changes to your `netlify.toml` for v2:

```toml
# netlify.toml

[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[dev]
  functions = "out_functions"
  publish   = "out_publish"
  framework = "#static"
```

And you will want to adjust your `.gitignore` for previewing locally:
```bash
# .gitignore

# Files generated by next-on-netlify command
/out_publish/
/out_functions/
/404.html
```

Let me know if you run into any trouble :upside_down_face: 

Happy hacking! :fire: 
Finn
