### ISSUE TITLE
Client-side routing not working

### ISSUE THREAD

**Issue by alxhghs** [FinnWoelm/next-on-netlify#22]
Hello! Thanks for all your hard work on this project.

Before V2 I used client-side routing but now I find that the links are not working. This applies to next/link as well as next/router. 

Please let me know if there is any more information I can provide or anything I can do to help.

**Comment by alxhghs** [comment]
I made a small demo repo and client side navigation is working fine. Closing this ticket.

**Comment by FinnWoelm** [comment]
Great to hear! :slightly_smiling_face: Look forward to tackling the issue with `getInitialProps` and client-side routing and `react-hook-form`!
