### ISSUE TITLE
Check if the configuration is a function.

### ISSUE THREAD

**Issue by pablo1v** [FinnWoelm/next-on-netlify#25]
It would be good to check if the user configuration is a function, as it is very common to use compose plugins ([next-compose-plugins](https://github.com/cyrilwanner/next-compose-plugins) for example) in next.js projects.

Ref: https://github.com/FinnWoelm/next-on-netlify/blob/8cca21a2a97c1c853316fed4ddf39c5daca72ee4/lib/getNextDistDir.js#L16-L24

**Comment by FinnWoelm** [comment]
Hi @pablo1v,

Sorry for the delayed reply! This is of course an excellent suggestion. I will implement that this weekend :blush:

**Comment by pablo1v** [comment]
Thanks!!

**Comment by FinnWoelm** [comment]
Fixed in freshly-released `next-on-netlify` v2.3.1 :blush: 

Thank you again for filing this issue! Let me know if you end up building something awesome with `next-on-netlify`. I would love to feature it in the README: https://github.com/FinnWoelm/next-on-netlify#showcase

**Comment by pablo1v** [comment]
I don't see any problem. 😆

The idea of ​​the project is wonderful!
I am grateful that my suggestion was of great importance.
