### ISSUE TITLE
Cannot build if custom distDir is specified

### ISSUE THREAD

**Issue by rfsbsb** [FinnWoelm/next-on-netlify#3]
Hey, nice work with this project!

I've noticed that when I specify a `distDir` different from `.next` on `next.config.js` it fails to run the postbuild.

I noticed that `NEXT_BUILD_PATH` const on `next-on-netlify.js` is hardcoded to look for `.next` folder.

**Comment by FinnWoelm** [comment]
Thank you for pointing that out, @rfsbsb!

I'm thinking that we could add support for specifying a custom NextJS directory as an argument. Something like:
```
next-on-netlify --next-dir ./custom/dir/
```

I haven't made my mind up about the actual syntax, but something like that. What do you think?

**Comment by rfsbsb** [comment]
I'd say it could get whatever is specified on `next.config.js` but an extra parameter should work as well...

**Comment by FinnWoelm** [comment]
Oh, you are right! Great point :grin: 

I'll make sure to pull in the setting from `next.config.js` then.

I think I can find time to do that this week. I will keep you posted!

**Comment by FinnWoelm** [comment]
@rfsbsb, happy to report that the freshly released v1.2.0 of `next-on-netlify` supports setting a custom `distDir` in `next.config.js`! Check it out and let me know if you run into any issues :blush: 

> ### v1.2.0:
> - Add support for custom NextJS build directory: If `distDir` is specified in  `next.config.js`, next-on-netlify will use that directory. If no `distDir` is  specified, it will look for the default directory (`.next`).

**Comment by rfsbsb** [comment]
Hey @FinnWoelm amazing! Thanks for letting me know! I'll run some tests!

**Comment by FinnWoelm** [comment]
Hey @rfsbsb, did you get a chance to test it out? Any issues? Otherwise, I'll go ahead and close this some time this coming week :slightly_smiling_face:

**Comment by FinnWoelm** [comment]
I'm closing this for now, but please feel free to re-open and comment at any time. :grin: 

For future reference, here is the commit that added support for custom distDir: https://github.com/FinnWoelm/next-on-netlify/commit/7c353b0fae7e514dcd04b3b74daf210d30fe5b17

**Comment by marengga** [comment]
Hi, I got a problem related to this issue while using this package

```
$ next-on-netlify
internal/validators.js:122
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:122:11)
    at join (path.js:1039:7)
    at getNextDistDir (/xxx/node_modules/next-on-netlify/lib/helpers/getNextDistDir.js:11:10)
    at Object.<anonymous> (/xxx/node_modules/next-on-netlify/lib/config.js:21:23)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
```

I tried to debug it and hardcoded getNextDistDir function to return ".next" and it works.
```

const getNextDistDir = () => {
  const nextConfig = getNextConfig();

  return join(".", ".next");
};
```

Adding distDir to next.config.js doesn't solved this. Still figuring it out what's wrong with this.
Any help would be appreciated

**Comment by jlengstorf** [comment]
@marengga could you give this a try with https://github.com/netlify/netlify-plugin-nextjs? this package has been absorbed into that project and automates a lot of the configuration (which should resolve this)

thanks!

**Comment by marengga** [comment]
Thanks for the clue, @jlengstorf. I just realized the plan to deprecate this package after re-reading the README.
Sure I'll give it a try!
