### ISSUE TITLE
Accessing public folder files?

### ISSUE THREAD

**Issue by hrahimi270** [FinnWoelm/next-on-netlify#31]
Hi there.
I'm using `next-i18next` for translations. The locale files are stored in `public/translations`.
As far as I know, Next automatically [servers the public folder](https://nextjs.org/docs/basic-features/static-file-serving), and it should have access to it!
When I deploy the project to Netlify, it seems the application does not have access to files. This is the error that shows me:
```js
{
  "errorType": "Error",
  "errorMessage": "ENOENT: no such file or directory, scandir '/var/task/public/translations/en'",
  "trace": [
    "Error: ENOENT: no such file or directory, scandir '/var/task/public/translations/en'",
    "    at Object.readdirSync (fs.js:948:3)",
    "    at getAllNamespaces (/var/task/src/out_functions/next_index/nextJsPage.js:124241:19)",
    "    at createConfig (/var/task/src/out_functions/next_index/nextJsPage.js:124246:27)",
    "    at new NextI18Next (/var/task/src/out_functions/next_index/nextJsPage.js:158492:48)",
    "    at Object.0v6L (/var/task/src/out_functions/next_index/nextJsPage.js:5428:18)",
    "    at __webpack_require__ (/var/task/src/out_functions/next_index/nextJsPage.js:31:31)",
    "    at Module.cha2 (/var/task/src/out_functions/next_index/nextJsPage.js:105080:15)",
    "    at __webpack_require__ (/var/task/src/out_functions/next_index/nextJsPage.js:31:31)",
    "    at Module.rxt/ (/var/task/src/out_functions/next_index/nextJsPage.js:146697:17)",
    "    at __webpack_require__ (/var/task/src/out_functions/next_index/nextJsPage.js:31:31)"
  ]
}
```

**Note:** the application works fine in Development and Production (next build & next start).

**Comment by FinnWoelm** [comment]
Hi @hrahimi270,

Were you able to figure everything out?

**Comment by hrahimi270** [comment]
Hi @FinnWoelm.
I solved my problem by updating the `next-i18next` package. In its previous version, I needed to set up a custom Nodejs server. And set the path for my translation files manually to the public folder. But in its new version, it doesn't need that. It moved the config to `next.config.js` and the problem solved.
