### ISSUE TITLE
Custom routing

### ISSUE THREAD

**Issue by Djepri** [FinnWoelm/next-on-netlify#4]
Hi could you tell me how to create a routing like below:
1. http://localhost:8888/g/lmB0i6Ybt~4
2. http://localhost:8888/search?keyword=foo bar

Thank you

**Comment by FinnWoelm** [comment]
Hey @Djepri,

Glad you figured it out! Let me know if you run into any issues in the future :slightly_smiling_face: 

Happy hacking! :fire: 
Finn

PS: Just released `next-on-netlify` v2 :tada: It adds support for `getStaticProps` and `getServerSideProps`, which may be of interest to you!
