### ISSUE TITLE
Support for target: 'experimental-serverless-trace'

### ISSUE THREAD

**Issue by theindiansoftwarecompany** [FinnWoelm/next-on-netlify#6]
Can you also add for `target: 'experimental-serverless-trace'`.
I'm using firebase, but the build returns an error:

> Build error occurred
Error: ENOENT: no such file or directory, open 'google/protobuf/api.proto'

Previously used, `target: 'serverless'` is going to be deprecated.

Reference: https://github.com/zeit/next.js/issues/11860

**Comment by FinnWoelm** [comment]
Hi @theindiansoftwarecompany,

Thank you for using next-on-netlify and for posting an issue here! :slightly_smiling_face: 

I had not heard of `target: 'experimental-serverless-trace'` before, but I just started some research and some experimentation.

I'm not super familiar with Firebase. Do you have a minimal repository that reproduces the issue? That would be super helpful!

We'll find a solution! Either by adding support for this new NextJS target or by manually including the `google/protobuf/api.proto` files. I found an interesting thread here: https://github.com/netlify/netlify-lambda/issues/112

**Comment by FinnWoelm** [comment]
I just tried spinning up a demo using `target: 'experimental-serverless-trace'`. It works!

- Repo: https://github.com/FinnWoelm/next-on-netlify-demo-serverless-trace
- Demo: https://next-on-netlify-demo-serverless-trace.netlify.app/

I basically just had to manually install three packages, that NextJS does not seem to bundle when using `experimental-serverless-trace`: `node-sass`, `sass`, and `fibers`:

```
npm install node-sass sass fibers
```

I'm not using Firebase, so we'll need to see how it works with that. If you can send a minimal repo, that would be awesome!

**Comment by FinnWoelm** [comment]
Hey @theindiansoftwarecompany,

Are you still needing support for this? Did you get a chance to set up a minimal repo where I can reproduce the error? I'm happy to look into it.

Otherwise, I'll be closing this issue in a few days. We can always reopen it if the need arises.

Hope you're doing well!

**Comment by FinnWoelm** [comment]
Hi @theindiansoftwarecompany,

I'm going to close this issue for now. Feel free to reopen it if you are still interested in resolving this issue! I'm here and happy to help :)

Happy hacking :fire: 
Finn
