### ISSUE TITLE
Local Preview: Static Routes not working

### ISSUE THREAD

**Issue by wei** [FinnWoelm/next-on-netlify#8]
Thanks for the great package!

I set up a brand new default Next.js install and added the code according to README.md

```
Page                                                           Size     First Load JS
┌ ○ /                                                          2.31 kB        65.4 kB
├ ○ /404                                                       3.15 kB        61.3 kB
└ λ /api/hello
+ First Load JS shared by all                                  58.2 kB
  ├ static/pages/_app.js                                       954 B
  ├ chunks/8e104c923a7c97406870fb6411b5f33e5dd2a109.1f6f8d.js  10.5 kB
  ├ chunks/framework.c6faae.js                                 40 kB
  ├ runtime/main.9e3c24.js                                     5.97 kB
  └ runtime/webpack.c21266.js                                  746 B

λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
```
#### `public/_redirects`
```
# Next-on-Netlify Redirects
/index  /_next/pages/index.html  200
/  /_next/pages/index.html  200
/404  /_next/pages/404.html  200
/_error  /.netlify/functions/nextRouter?_path=/_error  200
/api/hello  /.netlify/functions/nextRouter?_path=/api/hello  200
```

Note that the pages/index.js has no `getInitialProps`, `getServerSideProps`, or `getStaticProps`

The routes under `/.netlify/functions` works fine (e.g. `/api/hello`) but the routes pointing to `/_next` (`/`, `/index`, `/404`) do not work.

### After adding `getServerSideProps` to `pages/index.js`:
```
Page                                                           Size     First Load JS
┌ λ /                                                          6.97 kB        65.1 kB
├ ○ /404                                                       3.15 kB        61.3 kB
└ λ /api/hello
+ First Load JS shared by all                                  58.2 kB
  ├ static/pages/_app.js                                       954 B
  ├ chunks/9d5858f224b9f6cb55e0eaaa0a3efae572052440.1f6f8d.js  10.5 kB
  ├ chunks/framework.c6faae.js                                 40 kB
  ├ runtime/main.c2a2c7.js                                     5.97 kB
  └ runtime/webpack.c21266.js                                  746 B
```
#### New `public/_redirects`
```
# Next-on-Netlify Redirects
/404  /_next/pages/404.html  200
/_error  /.netlify/functions/nextRouter?_path=/_error  200
/api/hello  /.netlify/functions/nextRouter?_path=/api/hello  200
/index  /.netlify/functions/nextRouter?_path=/index  200
/  /.netlify/functions/nextRouter?_path=/  200
```

The routes `/`, `/index` now work fine as they are pointing to the function under `/.netlify/functions` but `/404` still does not work as it's pointing to files under `/_next/pages/404`.

**Comment by FinnWoelm** [comment]
Hi @wei,

Thanks for reaching out and sharing your issue! Glad you like the package :slightly_smiling_face: 

I tried to reproduce the issue ([next-on-netlify-demo-wei](https://github.com/FinnWoelm/next-on-netlify-demo-wei)), but everything works as expected:

- https://keen-poitras-5a801c.netlify.app/
- https://keen-poitras-5a801c.netlify.app/static

Could you share your source code with me? I'd like to have a closer look to understand what's going wrong.

**Comment by wei** [comment]
Thanks @FinnWoelm , after some testing, I noticed this issue only happens in the in [Preview Locally](https://github.com/FinnWoelm/next-on-netlify#preview-locally) with `netlify dev`. 

Please checkout my [fork](https://github.com/wei/next-on-netlify-demo-wei) and you should be able to reproduce with `npm run netlify:dev`. You can view my change [here](https://github.com/wei/next-on-netlify-demo-wei/commit/406054b9a7bb17102ab8810d8ba84b323412689b).

**Comment by FinnWoelm** [comment]
@wei, you are absolutely right! Good catch!

There are two issues at play here:

1. Netlify automatically detects the project as "NextJS" and, for some reason, that prevents all redirects other than to Netlify functions. See [this line in the netlify-cli dev script](https://github.com/netlify/cli/blob/a91c63c92c98bc4624156e78a1c36b721bdf84f8/src/commands/dev/index.js#L314). The solution is to explicitly set the framework to "#static" in `netlify.toml` — then redirects are applied again.

1. The `serve` returns a directory listing when `/` is visited. Netlify only performs redirects if the server returns a 404 (unless `force=true` is specified, but I'm trying to avoid doing that). But when we visit `/`, the server returns the directory listing (200) and thus Netlify does **not** redirect. There are two solutions to this:
  
    1. Keep using `serve` and add a `serve.json` file to the `public` directory that turns off the directory listings:
  
        ```
        {
          "directoryListing": false
        }
        ```

     1. Or install `http-server` instead of `serve` and modify `netlify.toml`: 

        ```
        [dev]
          command = http-server --port 3999 -d false -c-1 --silent`
        ```
        You will see that I've updated the guides to use this solution because it means creating one less file :slightly_smiling_face: 

You can see the commit I did on top of your code here: https://github.com/FinnWoelm/next-on-netlify-demo-wei/commit/a3783e1146b4cef8bbf9b641744e745a0929bf5a

Tested with `netlify-cli v2.48.0` (latest). Let me know if this works for you! :blush:

**Comment by wei** [comment]
It works great! Thanks for the quick and detailed response 🙇

**Comment by FinnWoelm** [comment]
Great to hear that! Hope you can build something awesome with it! :rocket: :slightly_smiling_face:

**Comment by FinnWoelm** [comment]
Just wanted to follow up on this thread and say that as of the more recent `netlify-cli` versions, netlify dev comes with its own static server.

So you no longer need to bring your own and can simply remove `serve` and/or `http-server`. One package less, yay :)
